FROM node:14.16

EXPOSE 5000

WORKDIR /usr/usr/app/

COPY . .

RUN npm install 
ENV REACT_APP_BACKEND_URL="http://localhost:8080/"
RUN npm run build

RUN npm install -g serve

RUN useradd -m appuser

USER appuser



CMD serve -s -l 5000 build