FROM node:14.16

EXPOSE 5000

WORKDIR /usr/usr/app/

COPY . .

RUN npm install 
#ADD ENV
ENV REACT_APP_BACKEND_URL="http://localhost:8080/"
RUN npm run build

RUN npm install -g serve



CMD serve -s -l 5000 build