version: '3'

services: 
    redis:
        image: redis
        ports: 
            - 6379:6379
    frontend:
        image: frontend
        ports: 
            - 5000:5000 
    backend:
        image: backend
        ports:
            - 8080:8080
        environment: 
            # redis host name will be given when default network is created. This one might not work and should be updated accordingly.
            REDIS_HOST: 24_redis_1
    