version: '3'

services: 
    redis:
        image: redis
        ports: 
            - 6379:6379
        container_name: redis_cont
    frontend:
        image: frontend
        ports: 
            - 5000:5000 
    backend:
        image: backend
        ports:
            - 8080:8080
        environment: 
           REDIS_HOST: redis_cont
    